/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rernas' at '3/6/17 8:34 PM' with Gradle 3.0
 *
 * @author rernas, @date 3/6/17 8:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
