/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rernas' at '3/3/17 5:26 PM' with Gradle 3.0
 *
 * @author rernas, @date 3/3/17 5:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
